### ISSUE TITLE
Parse string into cty type

### ISSUE THREAD

**Issue by chriskolenko** [zclconf/go-cty#162]
Is there any way to parse a string into a cty type?

Here's the string I have
```
list(object({
    domain_name         = string
    origin_id           = string
    origin_path         = optional(string)
    connection_attempts = optional(number)
    connection_timeout  = optional(number)
}))
```

**Comment by apparentlymart** [comment]
Hi @chriskolenko,

This library does have a function for parsing a standardized representation of types as _JSON_ -- [`UnmarshalType`](https://pkg.go.dev/github.com/zclconf/go-cty@v1.13.2/cty/json#UnmarshalType) -- but the syntax you've shared here seems like Terraform's type constraint syntax, which is outside of the scope of this library.

I would suggest instead studying the Terraform codebase to see how Terraform parses type constraint expressions like these. It should be possible in principle to replicate what Terraform does to arrive at a `cty.Type` value to pass to the "want" argument of [`convert.Convert`](https://pkg.go.dev/github.com/zclconf/go-cty@v1.13.2/cty/convert#Convert), which is what Terraform ultimately does with the type constraints in its language.
